DROP TABLE IF EXISTS aquapi;

CREATE TABLE config (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    configname TEXT NOT NULL,
    configvalue TEXT NOT NULL
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    userpassword TEXT NOT NULL
);

CREATE TABLE light (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lightchannel INTEGER NOT NULL,
    lighttime TEXT NOT NULL,
    lightvalue TEXT NOT NULL
);

CREATE TABLE history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hist_name TEXT NOT NULL,
    hist_value TEXT NOT NULL
);





