DROP TABLE IF EXISTS config;
CREATE TABLE config (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mqtt_host TEXT NOT NULL,
    mqtt_port INTEGER NOT NULL,
    mqtt_topic TEXT NOT NULL
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    userpassword TEXT NOT NULL
);

DROP TABLE IF EXISTS light;
CREATE TABLE light (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lightchannel INTEGER NOT NULL,
    lighttime TEXT NOT NULL,
    lightvalue TEXT NOT NULL
);

DROP TABLE IF EXISTS history;
CREATE TABLE history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hist_name TEXT NOT NULL,
    hist_value TEXT NOT NULL
);





